name: vipdopt3.10
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.*
  - scipy=1.12.0
  - numpy=1.26.*
  - numpy-stl=3.1.*
  - matplotlib=3.7.*
  - scikit-image=0.22.*
  - PyYAML=6.*
  - types-PyYAML=6.*
  - python-magic=0.4.*
  - Jinja2=3.1.*
  - PySide6=6.*
  - pip
  # For Linting
  - ruff=0.0.287
  # For static type checking
  - mypy=1.8.*
  - overrides=7.7.*
  # For testing
  - pytest=8.*
  - pytest-cov=4.1.*
  - pytest-xdist=3.5.*
  - pytest-mock=3.12.*
  - coverage[toml]=7.4.3