#* Debug

start_from_step: 2          # 0 if running entire file in one shot
shelf_fn: 'save_state'

restart_epoch: 0            # Both 0 if not restarting
restart_iter: 1

#* File Options

lumapi_filepath_local: "C:\\Program Files\\Lumerical\\v212\\api\\python\\lumapi.py"
lumapi_filepath_hpc: "/central/home/ifoo/lumerical/2021a_r22/api/python/lumapi.py"
#! do not include spaces in filepaths passed to linux

yaml_filename: 'test_config_sony.yaml'

#* Back-Compatibility

convert_existing: False     # Are we converting a previous file that didn't have the mode overlap FoM?

#* Mesh

mesh_spacing_um: 0.051
# geometry_spacing_minimum_um: 0.051    # NOTE: UNUSED
geometry_spacing_lateral_um: 0.051  #0.085    

device_scale_um: 0.051    # This is only used to scale vertical dimensions: focal length, device vertical layer voxels, and FDTD gap sizes.
# TODO: Consolidate with geometry_spacing_lateral_um

use_smooth_blur: False
min_feature_size_um: 0.085  # used only for blurring

#* Optical

background_index: 1.5   # TiO2
min_device_index: 1.5
max_device_index: 2.4   # SiO2

init_permittivity_0_1_scale: 0.5

focal_plane_center_lateral_um: 0

#* Device

num_vertical_layers: 10
vertical_layer_height_um: 0.204 #0.051 * 4 #0.017 * 8

device_size_lateral_um: 2.04 #2.125#2.091#2.04#2.091#2.04#geometry_spacing_lateral_um * 40

device_vertical_minimum_um: 0

#* Surroundings

# Structure the following list such that the last entry is the last medium above the device.
objects_above_device: [] #['permittivity_layer_substrate',
                        #'silicon_substrate']
num_sidewalls: 0
sidewall_thickness_um: 0.24
sidewall_material: 'etch'
sidewall_extend_focalplane: False
sidewall_vertical_minimum_um: -0.765

#* Spectral

add_infrared: False
lambda_min_um: 0.375
lambda_max_um: 0.725
lambda_min_eval_um: 0.375
lambda_max_eval_um: 0.725

num_bands: 3
num_points_per_band: 10 #20 #15

num_dispersive_ranges: 1

# Add PDAF Functionality
add_pdaf: False

pdaf_angle_phi_degrees: 45
pdaf_angle_theta_degrees: -8

pdaf_adj_src_idx: 0

#* FDTD

fdtd_simulation_time_fs: 600 #3000

#* Forward (Input) Source

weight_by_individual_wavelength: True   # At present this changes nothing.
use_gaussian_sources: True

use_airy_approximation: True
f_number: 2.2
airy_correction_factor: 0.84  # Approximation of central Airy lobe using a Gaussian profile
# See https://en.wikipedia.org/wiki/Airy_disk#Approximation_using_a_Gaussian_profile:~:text=to%20the%20intensity.-,Approximation%20using%20a%20Gaussian%20profile,-%5Bedit%5D

source_angle_theta_vacuum_deg: 0 #63
source_angle_phi_deg: 0

# General polarized source information
xy_phi_rotations: [0, 90]
xy_pol_rotations: [0, 90]
xy_names: ['x', 'y']

#* Adjoint Source

num_focal_spots: 4

# Determine which adjoint source goes to each dispersive range
# Each dispersive range itself contains a map for how the wavelength buckets correspond to which specific adjoint sources on the focal plane.
dispersive_range_to_adjoint_src_map: [
  [ 0, 1, 2, 3 ]
]

# Determine which dispersive range goes to each adjoint source
adjoint_src_to_dispersive_range_map: [
  0,
  0,
  0,
  0
]

#* Optimization

enforce_xy_gradient_symmetry: False #True#False#True

# Alternative is to weight by focal intensity - need to check max intensity weighting thing
weight_by_quadrant_transmission: True

#! 20230220 - Empirically, 300 iterations is usually the right number to get a stable optimization FoM.
num_epochs: 1 #10
num_iterations_per_epoch: 2 #30

use_fixed_step_size: False
fixed_step_size: 2.0

epoch_start_design_change_max: 0.15
epoch_end_design_change_max: 0.05
epoch_start_design_change_min: 0.05
epoch_end_design_change_min: 0

fom_types: ['transmission', 'intensity']
optimization_fom: 'intensity'    # Has to be one from the fom_types list

#* Spectral and polarization selectivity information

# Determine the polarizations that will be directed to each focal area
polarizations_focal_plane_map: [ ['x', 'y'], ['x', 'y'], ['x', 'y'], ['x', 'y'] ]

weight_focal_plane_map_performance_weighting: [ 1.0, 1.0, 1.0, 1.0 ]
weight_focal_plane_map: [ 1.0, 1.0, 1.0, 1.0 ]

do_green_balance: False #True

polarization_name_to_idx: { 'x':0, 'y':1, 'z':2 }

# desired_peaks_per_band_um: [ 0.46, 0.52, 0.61 ]
desired_peaks_per_band_um: [ 0.48, 0.52, 0.59 ]
# desired_peaks_per_band_um: [ 0.46, 0.52, 0.59 ]

explicit_band_centering: True
shuffle_green: False #True#False#True#False

infrared_center_um: 0.94
do_rejection: False
softplus_kappa:  2

